/*
REGLER:
1. Pulla github när du loggar in
    Detta görst genom TEAM -> REMOTE - > PULL
2. EDITA INTE SAMMA DOKUMENT, STFAFF = DÖDEN
3. PUSHA DITT ARBETE
    Commita först genom att: PROJECTS -> Schemanator -> GIT -> COMMIT
    Pusha sedan genom att: TEAM -> REMOTE -> PUSH
    HOPPAS PÅ DET BÄSTA, LYCKA TILL
*/
package main;
import Schema_relaterat.SchemaHanterare;
import Schema_relaterat.SchemaHändelse;
import Schema_relaterat.TidPunkt;
import java.awt.Button;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 * @author Måns Abrahamsson and Viggo Kött
 */
public class MainClass extends javax.swing.JFrame {
    
    //Variabler här:
     
    
    /**
     * Creates new form MainClass
     */
    public MainClass(int a) {
        initComponents();
        if(a==0){
            FrameInloggning inlogg = new FrameInloggning(); // skapar frame där schemat visas
            inlogg.setVisible(true); // schema frame tas fram och syns
            dispose(); // den här framen stängs ned
        }
        
        
        /*TableMåndag.setValueAt("Matte 3c 10:30 \n 11:30", 0, 0);
        TableMåndag.setRowHeight(0, 50);
        TableMåndag.setRowHeight(1, 25);
        DefaultTableModel model = (DefaultTableModel)TableMåndag.getModel();
        model.addRow(new Object[]{"Matte 4c! 12:30 13:30"});*/
    } // Faka you Månsineni neni

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schemaPanel1 = new main.SchemaPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(schemaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(schemaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainClass(0).setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.SchemaPanel schemaPanel1;
    // End of variables declaration//GEN-END:variables
}
